export const backgroundColor = '#282c34'
export const hoverColor = '#323842'
export const bodyColor = 'white'
export const secondaryColor = '#d6d6d6'
export const scrollbarThumbColor = '#fafafa'
export const positiveColor = '#3ea800'
export const negativeColor = '#ed271c'