export const backgroundColor = '#282c34'
export const bodyColor = 'white'
export const secondaryColor = 'slategray'
export const scrollbarThumbColor = '#fafafa'
export const positiveColor = 'green'
export const negativeColor = 'red'